### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by alvesisaque**
## Motivation

Updates all project documentation, including readme and more general structures

## Changes

- README.md
- code documentation
- update page documentation

### CODE REVIEW

**Review by apmt — COMMENTED** [review]
1. I guess the branch name could follow the [contribuition guilines](https://hygia-org.github.io/hygia/_sources/index.rst.txt) `x/issue_name`, where `x` represents the issue

**Comment by apmt** [comment]
2. Some links in the documentation are not working, like:
- Indices and tables -> [Index](https://hygia-org.github.io/hygia/genindex.html)
- Indices and tables -> [Module Index](https://hygia-org.github.io/hygia/py-modindex.html)
- Indices and tables -> [Search Page](https://hygia-org.github.io/hygia/search.html)
- [Show Source](https://hygia-org.github.io/hygia/_sources/doxygen/index.rst.txt)

**Comment by apmt** [comment]
3. I guess would be a good thing to try to fix the code blocs examples format, like in [here](https://hygia-org.github.io/hygia/doxygen/index.html#hygia.data_pipeline.feature_engineering.word_embedding.WordEmbedding)

**Comment by apmt** [comment]
4. We could also try to set [this ](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#confval-napoleon_use_param) sphinix param to True, in order to test if this would better format this part of the docstring:
```
:param df: Dataframe to extract word embedding features from.
:type df: pandas.DataFrame
:param column_name: Name of the column in the dataframe that contains the text data to extract features from.
:type column_name: str
:param normalize: Indicates whether to normalize the word embedding feature columns. Default is True.
:type normalize: bool, optional
```

**Review by Bruno-Felix — APPROVED** [review]
Show!!

**Pull request merged**
